### ISSUE TITLE
ReceiptService API  is missing  for printing Custom receipt format

### ISSUE THREAD

**Issue by DanyallAslam** [microsoft/Dynamics365Commerce.Solutions#135]
ReceiptService API  is missing  for printing Custom receipt format

ALL versions

Below mentioned Service is not available when we are migrating from RetailSDK to CommerceSDK under CRT extensions
![sssss](https://github.com/microsoft/Dynamics365Commerce.Solutions/assets/125641838/23f6567b-2ac0-4130-9741-459c3170dab0)

**Comment by DanyallAslam** [comment]
@madyke

**Comment by FedyukovDA** [comment]
Hi @DanyallAslam
ReceiptService should not be used directly. I would recommend to change process of getting receipt a little bit.
Create a PostTrigger for GetReceiptServiceRequest instead of Service. 
Here is a code sample which you can use:

```
public class GetReceiptServiceRequestTrigger : IRequestTriggerAsync
 {
        public IEnumerable<Type> SupportedRequestTypes => new[] { typeof(GetReceiptServiceRequest) };

        public Task OnExecuting(Request request)
        {
            return Task.CompletedTask;
        }

        public async Task OnExecuted(Request request, Response response)
        {
            var getReceiptServiceResponse = (GetReceiptServiceResponse)response;
            var getReceiptServiceRequest = (GetReceiptServiceRequest)request;

            RequestContext context = getReceiptServiceRequest.RequestContext;

            var shift = getReceiptServiceRequest.ShiftDetails;

            var nonNullReceipts = getReceiptServiceResponse.Receipts.Where(receipt => receipt != null);

            foreach (Receipt receipt in nonNullReceipts)
            {
                if (receipt.ReceiptType == ReceiptType.XReport)
                {
                     await this.Customize.XReport(receipt).ConfigureAwait(false);
                }
                else if (receipt.ReceiptType == ReceiptType.ZReport)
                {
                     await this.Customize.ZReport(receipt).ConfigureAwait(false);
                }
            }
        }
 }
```

**Comment by DanyallAslam** [comment]
> Hi @DanyallAslam ReceiptService should not be used directly. I would recommend to change process of getting receipt a little bit. Create a PostTrigger for GetReceiptServiceRequest instead of Service. Here is a code sample which you can use:
> 
> ```
> public class GetReceiptServiceRequestTrigger : IRequestTriggerAsync
>  {
>         public IEnumerable<Type> SupportedRequestTypes => new[] { typeof(GetReceiptServiceRequest) };
> 
>         public Task OnExecuting(Request request)
>         {
>             return Task.CompletedTask;
>         }
> 
>         public async Task OnExecuted(Request request, Response response)
>         {
>             var getReceiptServiceResponse = (GetReceiptServiceResponse)response;
>             var getReceiptServiceRequest = (GetReceiptServiceRequest)request;
> 
>             RequestContext context = getReceiptServiceRequest.RequestContext;
> 
>             var shift = getReceiptServiceRequest.ShiftDetails;
> 
>             var nonNullReceipts = getReceiptServiceResponse.Receipts.Where(receipt => receipt != null);
> 
>             foreach (Receipt receipt in nonNullReceipts)
>             {
>                 if (receipt.ReceiptType == ReceiptType.XReport)
>                 {
>                      await this.Customize.XReport(receipt).ConfigureAwait(false);
>                 }
>                 else if (receipt.ReceiptType == ReceiptType.ZReport)
>                 {
>                      await this.Customize.ZReport(receipt).ConfigureAwait(false);
>                 }
>             }
>         }
>  }
> ```

**Comment by awkaft** [comment]
Hi @FedyukovDA ,

We will like print the QR Code from these Method and Getting Error.

Retail proxy client offline request failed. RequestUri: crt://offline/SalesOrderManager/GetReceipts?queryResultSettings=SCRUBBED&Id=SCRUBBED&receiptRetrievalCriteria=SCRUBBED&$locale=SCRUBBED. Exception: System.IO.FileLoadException: Could not load file or assembly 'zxing, Version=0.16.7.0, Culture=neutral, PublicKeyToken=4e88037ac681fe60'. Could not find or load a specific file. (0x80131621)
File name: 'zxing, Version=0.16.7.0, Culture=neutral, PublicKeyToken=4e88037ac681fe60'
---> System.IO.FileLoadException: Could not load file or assembly 'zxing, Version=0.16.7.0, Culture=neutral, PublicKeyToken=4e88037ac681fe60'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Microsoft.Dynamics.Commerce.Runtime.Extensibility.Configuration.DirectoryAssemblyResolver.ResolveAssembly(Object sender, ResolveEventArgs args)
   at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
   at System.Runtime.Loader.AssemblyLoadContext.OnAssemblyResolve(RuntimeAssembly assembly, String assemblyFullName)
   at Contoso.GasStationSample.CommerceRuntime.GetReceiptServiceRequestTrigger.GetQrCode(String qrValue, Int32 size)
   at Contoso.GasStationSample.CommerceRuntime.GetReceiptServiceRequestTrigger.OnExecuted(Request request, Response response)
   at Microsoft.Dynamics.Commerce.Runtime.CommerceRuntime.RunOnExecutedTriggers(Request request, Response response, IEnumerable`1 triggers, SpanManager spanManager, Boolean isAsyncExecution)
   at Microsoft.Dynamics.Commerce.Runtime.CommerceRuntime.RunOnExecutedTriggers(Request request, Response response, IEnumerable`1 triggers, SpanManager spanManager, Boolean isAsyncExecution)
   at Microsoft.Dynamics.Commerce.Runtime.CommerceRuntime.ExecuteCore[TResponse](Request request, RequestContext context, IReadOnlyCollection`1 handlersToInvoke, Boolean skipRequestTriggers, Boolean isAsyncExecution)
   at Microsoft.Dynamics.Commerce.Runtime.CommerceRuntime.Execute[TResponse](Request request, RequestContext context, IReadOnlyCollection`1 handlersToInvoke, Boolean skipRequestTriggers, Boolean isAsync)
   at Microsoft.Dynamics.Commerce.Runtime.Workflow.GetReceiptRequestHandler.GetReceiptsForSalesTransaction(SalesOrder salesOrder, IEnumerable`1 receiptTypes, ReceiptRetrievalCriteria criteria, RequestContext requestContext)
   at Microsoft.Dynamics.Commerce.Runtime.Workflow.GetReceiptRequestHandler.Process(GetReceiptRequest request)
   at Microsoft.Dynamics.Commerce.Runtime.CommerceRuntime.ExecuteCore[TResponse](Request request, RequestContext context, IReadOnlyCollection`1 handlersToInvoke, Boolean skipRequestTriggers, Boolean isAsyncExecution)
   at Microsoft.Dynamics.Commerce.Runtime.CommerceRuntime.ExecuteCore[TResponse](Request request, RequestContext context, IReadOnlyCollection`1 handlersToInvoke, Boolean skipRequestTriggers, Boolean isAsyncExecution)
   at Microsoft.Dynamics.Commerce.Runtime.CommerceRuntime.Execute[TResponse](Request request, RequestContext context, IReadOnlyCollection`1 handlersToInvoke, Boolean skipRequestTriggers, Boolean isAsync)
   at Microsoft.Dynamics.Commerce.Runtime.Client.OrderManager.GetReceiptsAsync(String transactionId, ReceiptRetrievalCriteria receiptRetrievalCriteria, QueryResultSettings settings)
   at Microsoft.Dynamics.Commerce.RetailProxy.Adapters.AdaptorCaller.ExecuteMethod(Type managerType, MethodInfo methodInfo, HttpValueCollection httpValues)
   at Microsoft.Dynamics.Commerce.RetailProxy.Adapters.AdaptorCaller.CallCommerceRuntimeAsync(String allInOneUrlString)
   at Microsoft.Dynamics.Commerce.RetailProxy.Adapters.AdaptorCaller.ExecuteAsync(String allInOneUrl).

**Comment by FedyukovDA** [comment]
Hi @awkaft

Please, provide more information:
1) Detailed scenario what you are trying to do;
2) Version of FnO, CSU and StoreCommerce;
3) Which country/region code are used;

**Comment by DanyallAslam** [comment]
@FedyukovDA

we would lioke to generate QR code for that we use custom dll for generting QR code in CustomReceiveTRigger

FnO product version : 10.0.33 (10.0.1549.63)
Commerce app Version: 9.45.23154.2
RSSU Version: 9.45.23153.3

**Comment by FedyukovDA** [comment]
@DanyallAslam, Please create a new issue ticket for this problem. The original title is irrelevant to the current question. This will help us and other customers track the issues more easily. 
In a new issue don't forget to attach:
1) FnO, StoreCommerce, RSSU versions
2) Country\region
3) As I can see from the exception you are trying to do it in offline mode, please verify that it works in online as well;
4) We use zxing library version 0.16.6.991 in our code for EncodeQrCodeServiceRequest, do not reference version above in your code.
5) It will be great if you can attach your extension code for investigation.

**Comment by DanyallAslam** [comment]
@FedyukovDA  How could i use EncodeQrCodeServiceRequest in my code? give me some idea

**Comment by FedyukovDA** [comment]
> @FedyukovDA How could i use EncodeQrCodeServiceRequest in my code? give me some idea

@DanyallAslam You can find example of using that in this section of documentation https://learn.microsoft.com/en-us/dynamics365/commerce/localizations/ind-generate-qr-code-print-receipt?tabs=commerce-10-0-26#create-a-crt-extension-to-support-printing-qr-codes

**Comment by madyke** [comment]
Closing since original issue has been addressed. Please create a new issue if new questions come up.
